document:
  name: Regolamento del Consiglio Comunale di Palermo
  description: |
    Regolamento del Consiglio Comunale di Palermo.    
  tags:
    - consiglio comunale
    - regolamento
    - comune Palermo
